In [2]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
distances = np.matrix('0 3 2 4 1 1; \
                       3 0 1 1 3 2; \
                       2 1 0 2 2 1; \
                       4 1 2 0 4 3; \
                       1 3 2 4 0 1; \
                       1 2 1 3 1 0')
distances

matrix([[0, 3, 2, 4, 1, 1],
        [3, 0, 1, 1, 3, 2],
        [2, 1, 0, 2, 2, 1],
        [4, 1, 2, 0, 4, 3],
        [1, 3, 2, 4, 0, 1],
        [1, 2, 1, 3, 1, 0]])

In [26]:
distances[distances[:, 0] >= 2]

matrix([[3, 2, 4]])

In [31]:
condition = distances >= 2
rows, cols = np.where(condition)
print(rows[:])
print(cols)b

[[0 0 0 1 1 1 2 2 2 3 3 3 3 4 4 4 5 5]]
[[1 2 3 0 4 5 0 3 4 0 2 4 5 1 2 3 1 3]]


In [39]:
c = np.ones((6+1, 4+2), dtype=int)

In [40]:
c[0, :]= 0

In [37]:
for j in range(4+1):
        c[0, j] = 0

In [41]:
cb

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [42]:
import networkit as nk

In [44]:
g = nk.readGraph("Dolphin social network/dolphins.gml", nk.Format.GML)
n = g.numberOfNodes()

In [46]:
distances = np.zeros((n, n), dtype=np.int)

In [47]:
bfs = nk.graph.BFS(g, 0).run()

In [49]:
distances[0, :] = bfs.getDistances()

In [50]:
print(bfs.getDistances()[:15])
print(distances[0, :][:15])

[0.0, 3.0, 2.0, 2.0, 4.0, 5.0, 4.0, 2.0, 3.0, 5.0, 1.0, 4.0, 3.0, 4.0, 1.0]
[0 3 2 2 4 5 4 2 3 5 1 4 3 4 1]


In [56]:
test = list(range(10))
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
np.random.shuffle(test)

In [101]:
test[np.random.randint(0, 8)]

4

In [50]:
a = [1, 2, 3, 4, 5, -1, -1]
b = [4, 5, 6, 7, 8, 4, 8]

In [3]:
a -b 

{1, 2, 3}

In [63]:
na = np.array(list(a))
nb = np.array(list(b))

In [68]:
np.unique(nb).size

5

In [5]:
y = np.arange(10, 20)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
x = np.arange(5, 15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
x[np.nonzero(y < 15)]

array([5, 6, 7, 8, 9])

In [165]:
colors = np.arange(1, 1000001).reshape(1000, 1000)
colors[:15][:15]

array([[    1,     2,     3, ...,   998,   999,  1000],
       [ 1001,  1002,  1003, ...,  1998,  1999,  2000],
       [ 2001,  2002,  2003, ...,  2998,  2999,  3000],
       ..., 
       [12001, 12002, 12003, ..., 12998, 12999, 13000],
       [13001, 13002, 13003, ..., 13998, 13999, 14000],
       [14001, 14002, 14003, ..., 14998, 14999, 15000]])

In [117]:
distances = [[0, 3, 2, 4, 1, 1,],
             [3, 0, 1, 1, 3, 2],
             [2, 1, 0, 2, 2, 1],
             [4, 1, 2, 0, 4, 3],
             [1, 3, 2, 4, 0, 1],
             [1, 2, 1, 3, 1, 0]]
distances

[[0, 3, 2, 4, 1, 1],
 [3, 0, 1, 1, 3, 2],
 [2, 1, 0, 2, 2, 1],
 [4, 1, 2, 0, 4, 3],
 [1, 3, 2, 4, 0, 1],
 [1, 2, 1, 3, 1, 0]]

In [105]:
valid = colors[np.nonzero(distances[1, :][:6] >= 2), 1]
valid

array([[ 3, 27, 33]])

In [103]:
invalid = colors[np.nonzero(distances[:, 1] > 654), 3]
invalid

array([], shape=(1, 0), dtype=int64)

In [101]:
possible = np.setdiff1d(valid, invalid)
possible

array([ 2, 26, 32])

In [79]:
np.random.choice(possible, 1)

array([26])

In [81]:
np.amax(np.union1d(valid, invalid))

28

In [110]:
np.flatnonzero(distances[1, :][:6] >= 2)+1

array([1, 5, 6])

In [167]:
%timeit np.unique(colors[:, 0]).size

The slowest run took 7.70 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 43.6 µs per loop


In [172]:
%timeit m[1][1]

The slowest run took 10.13 times longer than the fastest. This could mean that an intermediate result is being cached 
10000000 loops, best of 3: 140 ns per loop


In [177]:
m = [[0 for x in range(5)] for x in range(5)] 
m[5]

IndexError: list index out of range

In [178]:
l = []


In [198]:
x = np.random.random_integers(0,100,1e7)

In [199]:
x.size

10000000

In [187]:
def npu():
    unique, counts = np.unique(x, return_counts=True)
    return unique

In [191]:
def pyu():
    return np.unique(x).size

In [200]:
%timeit npu()

1 loops, best of 3: 710 ms per loop


In [201]:
%timeit pyu()

1 loops, best of 3: 683 ms per loop
